version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    target-branch: dev
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]